port 26379
bind 127.0.0.1
protected-mode no

sentinel monitor carmine-v4-test 127.0.0.1 6380 2
sentinel down-after-milliseconds carmine-v4-test 2000
sentinel failover-timeout carmine-v4-test 5000
sentinel parallel-syncs carmine-v4-test 1
