#+STARTUP: overview, hidestars
#+TAGS: urgent underway maybe waiting hammock next
* DOCS
** Split README stuff up into GitHub wiki pages.                      :maybe:
** Mention need to migrate serialized data before v1.0.0 (incl. example)
This should be as simple as reading everything in (keys "*") and rewriting it
as is.
* API
** Pub/Sub reconnects support?                                      :waiting:
Waiting on Salvatore: https://github.com/antirez/redis/issues/420
Recall that reconnects would also require re-establishing p/subscriptions.

* TESTS                                                              :urgent:
** Unit-test for all other commands (adapt from redis-clojure!!).    :urgent:
** Unit-test for sort*.                                              :urgent:
Should be easily adaptable from redis-clojure
* PERFORMANCE
** Why is Jedis still so much faster than Carmine?
Profile and determine the exact bottlenecks. They may or may _not_ turn out to
be something we can (or even want to) fix.
** Update to newer Snappy version to fix OSX+JDK7 problem           :waiting:
** Look into using LZ4 instead of Snappy                              :maybe:
https://github.com/decster/jnicompressions
Also note the comments on that page about different interfaces!
https://github.com/ptaoussanis/carmine/issues/5
http://code.google.com/p/snappy-java/issues/detail?id=39

* MISC
** Finalize pull-request to be added to official client list.      :underway:
